CREATE TABLE IF NOT EXISTS courses (
    id SERIAL,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(6) NOT NULL UNIQUE PRIMARY KEY,
    description TEXT
);

CREATE TABLE IF NOT EXISTS students (
    id SERIAL,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(7) NOT NULL UNIQUE PRIMARY KEY
);